### PR TITLE
Update Fakeit to support scopes & collections

### PR DESCRIPTION
**Pull request by jgroh9**
# What was done

- I need scope and collection support when generating fake data. I've forked and updated FakeIt to support Couchbase scopes and collections. A PR was created for the work done in the FakeIt library however, I published a version of my fork to NPM so that we can take advantage of the FakeIt changes and do not have to wait on the team behind FakeIt to approve the PR which is a long shot given the last update to the project was 2-3 years ago. I've implemented the forked version of FakeIt in this PR.
- Decided to use a directory structure within the models directory to determine which scope and collection to insert data into. The structure needs to coincide with the scopes & collections that are in Couchbase.
- Added readme documentation on how to setup the directory structure in the models directory to achieve inserting data into the appropriate scope & collection
- Fixed a version comparison issue that created scopes & collections in Couchbase version 6
- Removed the FAKEIT_BUCKETTIMEOUT ENV variable as the value is the same as the default value already set within the FakeIt library

### CODE REVIEW

**Review by brantburnett — COMMENTED** [review]
I'm a bit hesitant to move to the separate fork of fakeit. Any chance you could work with Aaron (he works at Couchbase these days, actually) to get your work merged into the mainline?

Also, I noticed looking at your fork that you have a max version of Node set at 10. What was the reason for this, given that 14 is the current LTS? Compatibility issue?

**Comment by jgroh9** [comment]
@brantburnett I set it the version of Node to 10 in FakeIt because anything newer caused build issues. I do plan to make additional commits to fix the build issues with newer Node versions but I wanted to keep the PR for FakeIt as small as possible as it was getting pretty large already. I'm happy to work with the repo owner to get the PR merged however I didn't want to wait on them as I have no idea if they plan to maintain the repo or would accept PRs. It doesn't look like much work has been done on that repo for a long time. Would you be willing to accept this PR using the fork I made and I can create a new PR to change back to the original FakeIt library if my changes are accepted and pulled into that library?

**Comment by jgroh9** [comment]
I've updated FakeIt to use the latest Node SDK. In order to use the latest Node version of 15+ with this library, that required an update to the Couchbase library to use the latest version 3.1.0. Tested everything from Couchbase 6.0.3 to 7.0.0-beta

**Comment by brantburnett** [comment]
I'm certainly willing to consider it. I've also got an email into @bentonam to see what his interest level is. I may also just pull your work into my own fork and start using that.

My first concern is that we need to focus on how to cleanly approach scopes/collections on fakeit, independent of couchbasefakeit. We need to make sure we have a good, go-forward plan there. Otherwise, if the root fork goes in a different direction we'll end up on a permanently bifurcated strategy for model definitions on couchbasefakeit.

Since I didn't see the work on scopes/collections you did on your fakeit fork, can you describe a bit how you're approaching it?

**Comment by jgroh9** [comment]
Here are 2 commits that cover the changes related to scopes/collections in FakeIt. [Commit 1](https://github.com/bentonam/fakeit/pull/195/commits/503954cd4050c9db97344ec6c5a2caab2e1a9894) and [Commit 2](https://github.com/bentonam/fakeit/pull/195/commits/b72465cdb0a990f8545cfa1ed58d62e5b20a346c). The gist of it is that you provide either a scope name and/or a collection name to generate the data in. This corresponds with the changes made in this library and how the Couchbase Node SDK handles scopes and collections. If you do not provide a scope or collection, the default scope and collection are used. The other updates to the FakeIt library are all focused on updating the dependencies to remove security vulnerabilities and make the library more maintainable going forward.

**Comment by brantburnett** [comment]
Okay, my key concern there is that it seems limited to command line parameters. While less likely with scopes, I fully expect models in fakeit to be spread across multiple collections. Under the new paradigm, a collection will generally be the equivalent to what Couchbase has historically used the "type" attribute to accomplish. Each document "type" would reside in its own collection. Of course, it may be used in many different ways, but I'd predict that this is the most common.

Therefore, I would think that defining the scope/collection in the model file itself makes sense.

Currently, the top of the model may look something like this:

```yaml
name: Types example
# typically object or array
type: object
key:
  build: faker.random.uuid()
```

I would think that something like this would be nice for scopes/collections:

```yaml
name: Types example
# typically object or array
type: object
key:
  build: faker.random.uuid()
scope:
  value: my_microservice
collection:
  value: my_collection
```

It could also support the full range of generation options using build, like key. And if not present, defaults back to `_default`.

What are your thoughts?

Overall, here is my proposal for you to consider. I'm hesitant to put such a large changeset of fakeit into couchbasefakeit without a bit more oversight, given that any regressions could negatively impact a lot of people. Not least of which is me, my company uses CouchbaseFakeIt extensively for CI/CD testing flows. If something goes wonky, it won't be a good day at the office for me 😄.

What if we do this?:

1. We do the changes to fakeit as PRs into my fork of fakeit (https://github.com/brantburnett/fakeit/tree/master)
2. We start off with a PR (or PRs) just to bring the dependencies up to date, without any behavioral changes
3. After that, we move forward with work on scopes/collections (this will help clean things up a bit, you have a lot of little commits in the history in your fork)
4. I'll work with @bentonam to see if he wants to move it forward from my fork after we're done
5. We'll update couchbasefakeit to use either my fork or the root, depending

Side note: You should probably take a minute to look at the "dev" branch. I know they were working on a 2.0 release with some refactoring in that branch back in 2018, not sure where that stands.

Anyway, this will allow me to review and test the changes as we go. I'm a big fan of breaking down work into small but complete units of work that are easier to grok (as you may have noticed from the way we've split up the work so far).

Thanks,
Brant

**Comment by jgroh9** [comment]
I'm going to close this PR. I've implemented scopes and collections in the FakeIt library via defining them in the model definitions, therefore this PR is no longer valid.

**Pull request closed without merging**
